### ISSUE TITLE
What version of ink is this integrated with?

### ISSUE THREAD

**Issue by nroca** [koomai/bulletproof-email#2]
Curious as to what other bugs may not be patched. Thanks, may consider updating this and creating a pull request. Though it seems you chopped up the CSS and put it into their individual files. May consider using bower to load it into the project as a dependency to make it easier to update.

**Comment by koomai** [comment]
The Zurb Ink code is in there more as a demonstration of how to break down and organise your css for maintainability. You don't necessarily need to use it, hence it's not there as a dependency. Also, I'd hate to add one monolithic css file and then override everything in sass.

In any case, I've left the version info found at the top of Zurb's ink.css file. That would be in the reset module - https://github.com/koomai/bulletproof-email/blob/master/source/stylesheets/modules/_reset.scss
