### ISSUE TITLE
Using @font-face with template builder

### ISSUE THREAD

**Issue by Jones-S** [koomai/bulletproof-email#7]
Hi

I am currently trying out your template builder and it seems nice so far.
I use it to build Mailchimp templates and I started to add mailchimp specific tags and syntax snippets, which seems to work nicely.

I also want to support the «experimental» feature where I can use webfonts – at least for the few clients who support it:
https://templates.mailchimp.com/design/typography/

I think that the template builder when building does not place the `@font-face` piece of code in the html, and therefor it won't appear in the imported template at mailchimp.

Is there a way to not delete that part and leave it in the `<style>` section within the head?

Thanks for your feedback.

cheers

**Comment by Jones-S** [comment]
Sorry.  I just realized after sending this issue that I can include it like you do it with the media queries... I will try that right now.

**Comment by Jones-S** [comment]
I got it to work. Just like the mediaqueries

**Comment by koomai** [comment]
Sorry I couldn't help - haven't worked on this repo in a long time. Great that you figured it out yourself. 👍🏼
